# Settings for song rendering
lyrics_font: ptm

# Default colors for section types (x11 color names)
colors:
  intro: buff
  couplet: brightgreen
  couplet2: darkgreen!30
  couplet3: darkgreen!60
  prerefrain: bubbles
  prerefrain1: blue
  refrain: columbiablue
  refrainb: brightturquoise
  pont: thistle
  outro: Aquamarine2
  solo: candyapplered!65
  interlude: tangerine
  riff: timberwolf
  fill: Aquamarine2!10
  final: Aquamarine2
